theme: jekyll-theme-minimal

# jekyll-seo-tag
title:           Masterâ€™s in Data Science Postgraduate Student at UKM
#tagline:
description:    "Data Enthusiast that actively augmenting knowledge and skill in data mining, analytic and machine learning"
#url:           https://yeetornghoo.github.io/
#author:        yeetornghoo
logo:           /docs/profile.png
